server:
  port: 8888

spring:
  application:
    name: config-service
    
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  cloud:
    config:
      server:
        git:
          uri: https://github.com/JeminLim/mentoree-config.git # 매칭이 안된 config 파일에 대한 탐색 경로
          repos:
            auth:
              pattern: "*auth*"
              uri: git@github.com:JeminLim/mentoree-private-config.git
              privateKey:
                -----BEGIN OPENSSH PRIVATE KEY-----
                b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABAzmyCaN0
                KMrG1BzeknFvwyAAAAEAAAAAEAAAGXAAAAB3NzaC1yc2EAAAADAQABAAABgQC+M2XxS+lu
                Sl7Ip/mETV26h60kOWZBInGFj7OQGce8GBufjomX7QdQjTNVqxB0p/sdrsNkxF0do8+JLS
                K920mVSy+oD58yXhe8GJH6ELQKOvtW4bxKVOFgnvJbAFnspeFmzT0PHLKlh3g/lGu/9PzO
                aijRWsckuvWcFpnhXgcVkRPaL4vZCocdETNBdSwWjjbgDEpJ8HyjKXI7eZsuaV2xi8zZgc
                QDPGKw74USEJpSWI2bBdovdV7ca16najDJNqeJtVLZ2rhgVwtpSlt955uglF5z5ohW2KOL
                r0UJlyaZrqtwYAZWjDQsgVoKHA/pZEVJDzSGa13phv3UFnZBmX1FZI1R5i9NdzzRxetBnD
                VnVuUunMcCcoq0TSH4zRn8szLDkfewNIe8JyEbK/712qKPFUww0ZNlHUSWoYOIXEkzXDvZ
                wFmvqj5H26pdmXW8+l8fyv3IPQUZT5ipZXQVYce/ura9FlOvY2GQexsZ2UbsG87sTavepm
                j2BIlrG/y3kgsAAAWQi/nNC1mQRfUG15IVZGkaPLjmf960yWIl1BT3jc1cDOULdRbbZ5SJ
                m1lGEN2oN2Ct/aNG7fvV7W2serx4BFVK9m3MY4ZIQKk+bicvVstjs8qbIqbs+NuyU/ndVz
                qtoqVzqXTnjk5q1uXV9uvLw1VyNFjDYLmT7R8ZEwB3Ol2JYqfBCEyaXpHO5AqAZu9RnkK7
                bwC2SoanHW4DQbL9iD5efUQEPi0ckc1bvdbfzzYiuQhWRSXfaj9ZaxTbJ1ob3rQ7BUn8ME
                2uO92Ir7ViiXzVjAmV87afS/tFkNktyDtgS44SNFJwZ1SJnDCPtj1+6BEQ61wFItbvNnnG
                zfOlgJ0qCT0D4EFmMLd8kHZ8tybVl92IpBgLQB2fsHHym6Yljzcf6LRzv6ZS4zI/dZloXs
                zqDf8H+V3B3voyBCOveFXBAm6r+Ud9+llYzQ/0WkMDauluJ0VE2AJPp6ibVEfrGTVXBrQw
                CBmbqrdxyzkLLpVRCR1slJsm31IVjaw9SpEGOte8U9vfsg2bEsJF/Q4neIekbRFTLZnk01
                mAN0a0zSUDtf5UuB1GtTgNUlNlji57nqJi1HVaBugT+GZ20VM0F5FRJjwC2gLzs6GhfDP/
                hwsxsmxS1WFk56buxX1ID0w9SONjyE+WWSmUb/9tRlc4FOc4+x82+LSjmV+dGfnxjpXC3a
                K+ylfEbGqLAH5K+cEAck0tqlPTykpSQ1S66pC6gvlxjRQIe2gUtjF4skv6nGDtcEVRt2cP
                Pp7r9dlGX9JQCvAB0pze3ke1n9uf7hjLU3FWFHTqOrhuTZZFmywK2PFagu6Qwml1JWbSx2
                CkchsJD6FkST8BKTvNR7MASjVjOlhWaJaKhjtsx9tw6iJ/dpOJwrDPwWqyzyk8eNnFPROH
                89SxABXvmizjTtfqDLiysIQs/8+4NwjICRd+hIhv74oaIG23GVWteP8lMt5MJLMJEGmC91
                2tSsZUg2tSLtLxReIBHljc+7mSL0+A38o2ERrv+Pl37Qv3Csb6EpiwzU+j3tNyDaUe/Prw
                S4j7PNVI8vZE8rKfJ33haNypqHvN8y//GOnoDGjOF6ghep9N/ihYCOGZzqENtG1NyCtICq
                6Qu/E6qho40peJqIx04FUXKb+PyGLkGpKPP/IyYF/0JBi4CQN/iQAIMaRRFcBtUaN0O4ad
                zet0RX0qg0teCfAEuOSSksqgwqMeBgJdaHw8vjhob5EZ1J8G+Im0ZlapaJg2x343aLLYiK
                LshTbwspKq718MPnlKL7Orbn77kLn2v+Tb8p1AxKKNiSkVljLm+Dwn/41Br42fk6xQVQdL
                Jf6p1InCATiXVu9nP1kImK/kHKkWRmLvlrR4JkOWCEmDCWqkV6aiLRvxx+lH9NCkTQbeq3
                kQ2lDFNTSI9BinjDaWZ7xqYMg140ksLZpEfKVyO/xU1UVDNIwpI1YzFBuG0NydTRy18kt1
                VD93MuwGDvzlaw2+d8Gbj7SHzAo1d1Du4teliK+UTnggHc13rD8lKMdNnWLSvX1Rva54tn
                bVJv3W5B1IASadWpk8PgDGjwRDuUmsSyDCjiFpqNth21sACoQB1FVY22C3BL+rfLRgPtEK
                4lDqkKkSeOMXSBD8WFnWxiGnZa+xfX4oAMThu9xlwHXcazT6wZRq0ea5XgWVO3uNDy8NTv
                Ht55Ip8y9wi3enRXtkAbmsOLdKa6n4+RJzIVjJ0QGcZlaZgJtDc2JcM60vv4EmOqr54oGu
                WoW2cT4AO4VOxIIjdM3hP2mFwgWSW2OP9bam2sP4j6v7We9cu3kkYl0Ae1TrOHDWqPbGP0
                wsgFUaSU+95JZBUOS22HRvf0YAyxlC2zr5Hb3M3cW8cTKxoBIxZGFcjYTvwEaf5CIYb9am
                bkBQ4zcvJ367gCQ2zQ06P3aeASM=
                -----END OPENSSH PRIVATE KEY-----

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, refresh
