language: java
jdk:
- openjdk11
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
before_install:
- openssl aes-256-cbc -K $encrypted_2225e3c30702_key -iv $encrypted_2225e3c30702_iv -in config-info.tar.enc -out config-info.tar -d
- chmod +x gradlew
- tar xvf config-info.tar
- mkdir -p ./infra/config-server/src/main/resources
- mv application.yml ./infra/config-server/src/main/resources
- mv bootstrap.yml ./infra/config-server/src/main/resources
- mv apiEncryptionKey.jks ./infra/config-server
script:
- echo "> build api-gateway-service"
- "./gradlew clean :infra-api-gateway-service:build"
- echo "> build eureka-server"
- "./gradlew clean :infra-eureka-server:build"
- echo "> build config-server"
- "./gradlew clean :infra-config-server:build"
- echo "> build member-service"
- "./gradlew clean :member-app-api:build"
- echo "> build member-auth-servicee"
- "./gradlew clean :member-app-auth-server:build"
- echo "> build mentoring-service"
- "./gradlew clean :mentoring-app-api:build"
- echo "> build reply-service"
- "./gradlew clean :reply-app-api:build"
before_deploy:
- zip -r mentoree-webservice *
- mkdir -p deploy
- mv mentoree-webservice.zip deploy/mentoree-webservice.zip
deploy:
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: mentoree-build
  region: ap-northeast-2
  skip_cleanup: true
  acl: private
  local_dir: deploy
  wait-until-deployed: true
  on:
    all_branches: true
- provider: codedeploy
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: mentoree-build
  key: mentoree-webservice.zip
  bundle_type: zip
  application: mentoree-webservice-codedeploy
  deployment_group: mentoree-webservice-group
  region: ap-northeast-2
  wait-until-deployed: true
notifications:
  email:
    recipients:
    - wer0801@gmail.com
