language: java
jdk:
  - openjdk11

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script:
  - echo "> build api-gateway-service"
  - "./gradlew :infra-api-gateway-service:build"
  - echo "> build eureka-server"
  - "./gradlew :infra-eureka-server:build"

before_install:
  chmod +x gradlew

notifications:
  email:
    recipients:
      - wer0801@gmail.com