version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      mentoree-network-net:
        ipv4_address: 172.18.0.100
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 43.200.50.181
      KAFKA_CREATE_TOPICS: "member-profile-update-topic"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      mentoree-network-net:
        ipv4_address: 172.18.0.101

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports: 
      - "15672:15672" 
      - "5672:5672" 
      - "15671:15671" 
      - "5671:5671" 
      - "4369:4369"
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - mentoree-network-net

  mentoree-redis:
    image: redis
    container_name: mentoree-redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - mentoree-network-net

  mentoree-front:
    image: wer080/mentoree-front:1.0
    container_name: mentoree-front
    command: real
    ports:
      - "8081:8081"
    restart: always
    networks:
      - mentoree-network-net

  infra-config-server:
    image: wer080/infra-config-server:1.0
    container_name: infra-config-server
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    ports:
      - "8888:8888"
    restart: always
    environment:
      - spring.rabbitmq.host=rabbitmq 
    networks:
      - mentoree-network-net

  infra-erueka-server:
    image: wer080/infra-eureka-server:1.0
    container_name: infra-eureka-server
    depends_on:
      - infra-config-server
    ports:
      - "8761:8761"
    restart: always
    environment:
      - spring.cloud.config.uri=http://infra-config-server:8888
    networks:
      - mentoree-network-net

  infra-api-gateway-service:
    image: wer080/infra-api-gateway-service:1.0
    container_name: infra-api-gateway-service
    depends_on:
      - mentoree-front
      - infra-config-server
      - infra-eureka-server
      - mentoree-redis
      - rabbitmq
    links:
      - mentoree-front
      - infra-config-server
      - infra-eureka-server
      - mentoree-redis
      - rabbitmq
    ports:
      - "8000:8000"
    restart: always
    environment:
      - front.url=http://mentoree-front:8081
      - spring.cloud.config.uri=http://infra-config-server:8888
      - spring.redis.host=http://mentoree-redis:6379
      - spring.rabbitmq.host=rabbitmq
      - Kafka.client.url=http://kafka:9092
      - eureka.client.serviceUrl.defaultZone=http://infra-eureka-server:8761/eureka/
      - server.url=http://43.200.50.181:8000
    networks:
      - mentoree-network-net

networks:
  mentoree-network-net:
    external:
      name: mentoree-network