version: "3"

services:
  infra-api-gateway-service:
    image: wer080/infra-api-gateway-service:1.0
    container_name: infra-api-gateway-service
    depends_on:
      - mentoree-front
      - infra-config-server
      - infra-eureka-server
      - mentoree-redis
      - rabbitmq
    links:
      - mentoree-front
      - infra-config-server
      - infra-eureka-server
      - mentoree-redis
      - rabbitmq
    ports:
      - "8000:8000"
    restart: always
    environment:
      - front.url=http://mentoree-front:8081
      - spring.cloud.config.uri=http://infra-config-server:8888
      - spring.redis.host=http://mentoree-redis:6379
      - spring.rabbitmq.host=rabbitmq
      - Kafka.client.url=http://kafka:9092
      - eureka.client.serviceUrl.defaultZone=http://infra-eureka-server:8761/eureka/
      - server.url=http://43.200.50.181:8000
    volumes:
      - .:/mentoree
    networks:
      - mentoree-network
  member-auth-service:
    image: wer080/member-auth-service:1.0
    container_name: member-auth-service
    depends_on:
      - infra-config-server
      - infra-eureka-server
      - mentoree-redis
      - kafka
      - rabbitmq
    links:
      - infra-config-server
      - infra-eureka-server
      - mentoree-redis
      - kafka
      - rabbitmq
    environment:
      - spring.cloud.config.uri=http://infra-config-server:8888
      - spring.redis.host=http://mentoree-redis:6379
      - spring.rabbitmq.host=rabbitmq
      - Kafka.client.url=http://kafka:9092
      - Feign.url=http://43.200.50.181:8000
      - eureka.client.serviceUrl.defaultZone=http://infra-eureka-server:8761/eureka/
      - PROFILE=real
    restart: always
    volumes:
      - .:/mentoree
    networks:
      - mentoree-network

  member-service:
    image: wer080/member-service:1.0
    container_name: member-service
    depends_on:
      - infra-config-server
      - infra-eureka-server
      - mentoree-redis
      - kafka
      - rabbitmq
    links:
      - infra-config-server
      - infra-eureka-server
      - mentoree-redis
      - kafka
      - rabbitmq
    environment:
      - spring.cloud.config.uri=http://infra-config-server:8888
      - spring.redis.host=http://mentoree-redis:6379
      - spring.rabbitmq.host=rabbitmq
      - Kafka.client.url=http://kafka:9092
      - Feign.url=http://43.200.50.181:8000
      - eureka.client.serviceUrl.defaultZone=http://infra-eureka-server:8761/eureka/
      - PROFILE=real
    restart: always
    volumes:
      - .:/mentoree
    networks:
      - mentoree-network

  mentoring-service:
    image: wer080/mentoring-service:1.0
    container_name: mentoring-service
    depends_on:
      - infra-config-server
      - infra-eureka-server
      - mentoree-redis
      - kafka
      - rabbitmq
    links:
      - infra-config-server
      - infra-eureka-server
      - mentoree-redis
      - kafka
      - rabbitmq
    environment:
      - spring.cloud.config.uri=http://infra-config-server:8888
      - spring.redis.host=http://mentoree-redis:6379
      - spring.rabbitmq.host=rabbitmq
      - Kafka.client.url=http://kafka:9092
      - Feign.url=http://43.200.50.181:8000
      - eureka.client.serviceUrl.defaultZone=http://infra-eureka-server:8761/eureka/
      - PROFILE=real
    restart: always
    volumes:
      - .:/mentoree
    networks:
      - mentoree-network

  reply-service:
    image: wer080/reply-service:1.0
    container_name: reply-service
    depends_on:
      - infra-config-server
      - infra-eureka-server
      - mentoree-redis
      - kafka
      - rabbitmq
    links:
      - infra-config-server
      - infra-eureka-server
      - mentoree-redis
      - kafka
      - rabbitmq
    environment:
      - spring.cloud.config.uri=http://infra-config-server:8888
      - spring.redis.host=http://mentoree-redis:6379
      - spring.rabbitmq.host=rabbitmq
      - Kafka.client.url=http://kafka:9092
      - Feign.url=http://43.200.50.181:8000
      - eureka.client.serviceUrl.defaultZone=http://infra-eureka-server:8761/eureka/
      - PROFILE=real
    restart: always
    volumes:
      - .:/mentoree
    networks:
      - mentoree-network
networks:
  mentoree-network:
    driver: bridge
    external: true
    internal: true