version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports: 
      - "15672:15672" 
      - "5672:5672" 
      - "15671:15671" 
      - "5671:5671" 
      - "4369:4369"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - mentoree-network

  mentoree-redis:
    image: redis
    container_name: mentoree-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - mentoree-network

  mentoree-front:
    image: wer080/mentoree-front:1.0
    container_name: mentoree-front
    command: real
    ports:
      - "8081:8081"
    networks:
      - mentoree-network

  infra-config-server:
    image: wer080/infra-config-server:1.0
    container_name: infra-config-server
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    ports:
      - "8888:8888"
    environment:
      - spring.rabbitmq.host=rabbitmq 
    networks:
      - mentoree-network

  infra-erueka-server:
    image: wer080/infra-eureka-server:1.0
    container_name: infra-eureka-server
    depends_on:
      - infra-config-server
    ports:
      - "8761:8761"
    environment:
      - spring.cloud.config.uri=http://infra-config-server:8888
    networks:
      - mentoree-network

  #depends_on 과 link의 차이점 공부
  infra-api-gateway-service:
    image: wer080/infra-api-gateway-service:1.0
    container_name: infra-api-gateway-service
    depends_on:
      - mentoree-front
      - infra-config-server
      - infra-eureka-server
      - mentoree-redis
      - rabbitmq
    links:
      - mentoree-front
      - infra-config-server
      - infra-eureka-server
      - mentoree-redis
      - rabbitmq
    ports:
      - "8000:8000"
    environment:
      - front.url=http://mentoree-front:8081
      - spring.cloud.config.uri=http://infra-config-server:8888
      - spring.redis.host=http://mentoree-redis:6379
      - spring.rabbitmq.host=rabbitmq
      - Kafka.client.url=http://43.200.50.181:9092
      - eureka.client.serviceUrl.defaultZone=http://infra-eureka-server:8761/eureka/
      - server.url=http://43.200.50.181:8000
    networks:
      - mentoree-network

  member-auth-service:
    image: wer080/member-auth-service:1.0
    container_name: member-auth-service
    depends_on:
      - infra-config-server
      - infra-eureka-server
      - mentoree-redis
      - rabbitmq
    links:
      - infra-config-server
      - infra-eureka-server
      - mentoree-redis
      - rabbitmq
    environment:
      - spring.cloud.config.uri=http://infra-config-server:8888
      - spring.redis.host=http://mentoree-redis:6379
      - spring.rabbitmq.host=rabbitmq
      - Kafka.client.url=http://43.200.50.181:9092
      - Feign.url=http://43.200.50.181:8000
      - eureka.client.serviceUrl.defaultZone=http://infra-eureka-server:8761/eureka/
      - PROFILE=real
    networks:
      - mentoree-network

  member-service:
    image: wer080/member-service:1.0
    container_name: member-service
    depends_on:
      - infra-config-server
      - infra-eureka-server
      - mentoree-redis
      - rabbitmq
    links:
      - infra-config-server
      - infra-eureka-server
      - mentoree-redis
      - rabbitmq
    environment:
      - spring.cloud.config.uri=http://infra-config-server:8888
      - spring.redis.host=http://mentoree-redis:6379
      - spring.rabbitmq.host=rabbitmq
      - Kafka.client.url=http://43.200.50.181:9092
      - Feign.url=http://43.200.50.181:8000
      - eureka.client.serviceUrl.defaultZone=http://infra-eureka-server:8761/eureka/
      - PROFILE=real
    networks:
      - mentoree-network

  mentoring-service:
    image: wer080/mentoring-service:1.0
    container_name: mentoring-service
    depends_on:
      - infra-config-server
      - infra-eureka-server
      - mentoree-redis
      - rabbitmq
    links:
      - infra-config-server
      - infra-eureka-server
      - mentoree-redis
      - rabbitmq
    environment:
      - spring.cloud.config.uri=http://infra-config-server:8888
      - spring.redis.host=http://mentoree-redis:6379
      - spring.rabbitmq.host=rabbitmq
      - Kafka.client.url=http://43.200.50.181:9092
      - Feign.url=http://43.200.50.181:8000
      - eureka.client.serviceUrl.defaultZone=http://infra-eureka-server:8761/eureka/
      - PROFILE=real
    networks:
      - mentoree-network

  reply-service:
    image: wer080/reply-service:1.0
    container_name: reply-service
    depends_on:
      - infra-config-server
      - infra-eureka-server
      - mentoree-redis
      - rabbitmq
    links:
      - infra-config-server
      - infra-eureka-server
      - mentoree-redis
      - rabbitmq
    environment:
      - spring.cloud.config.uri=http://infra-config-server:8888
      - spring.redis.host=http://mentoree-redis:6379
      - spring.rabbitmq.host=rabbitmq
      - Kafka.client.url=http://43.200.50.181:9092
      - Feign.url=http://43.200.50.181:8000
      - eureka.client.serviceUrl.defaultZone=http://infra-eureka-server:8761/eureka/
      - PROFILE=real
    networks:
      - mentoree-network

networks:
  mentoree-network:
    name: mentoree-network
    external: true