version: "3"

services:
  member-auth-service:
    image: wer080/member-auth-service:1.0
    container_name: member-auth-service
    depends_on:
      - infra-config-server
      - infra-eureka-server
      - mentoree-redis
      - rabbitmq
    links:
      - infra-config-server
      - infra-eureka-server
      - mentoree-redis
      - rabbitmq
    environment:
      - spring.cloud.config.uri=http://infra-config-server:8888
      - spring.redis.host=http://mentoree-redis:6379
      - spring.rabbitmq.host=rabbitmq
      - Kafka.client.url=http://kafka:9092
      - Feign.url=http://43.200.50.181:8000
      - eureka.client.serviceUrl.defaultZone=http://infra-eureka-server:8761/eureka/
      - PROFILE=real
    restart: always
    networks:
      - mentoree-network

  member-service:
    image: wer080/member-service:1.0
    container_name: member-service
    depends_on:
      - infra-config-server
      - infra-eureka-server
      - mentoree-redis
      - rabbitmq
    links:
      - infra-config-server
      - infra-eureka-server
      - mentoree-redis
      - rabbitmq
    environment:
      - spring.cloud.config.uri=http://infra-config-server:8888
      - spring.redis.host=http://mentoree-redis:6379
      - spring.rabbitmq.host=rabbitmq
      - Kafka.client.url=http://kafka:9092
      - Feign.url=http://43.200.50.181:8000
      - eureka.client.serviceUrl.defaultZone=http://infra-eureka-server:8761/eureka/
      - PROFILE=real
    restart: always
    networks:
      - mentoree-network

  mentoring-service:
    image: wer080/mentoring-service:1.0
    container_name: mentoring-service
    depends_on:
      - infra-config-server
      - infra-eureka-server
      - mentoree-redis
      - rabbitmq
    links:
      - infra-config-server
      - infra-eureka-server
      - mentoree-redis
      - rabbitmq
    environment:
      - spring.cloud.config.uri=http://infra-config-server:8888
      - spring.redis.host=http://mentoree-redis:6379
      - spring.rabbitmq.host=rabbitmq
      - Kafka.client.url=http://kafka:9092
      - Feign.url=http://43.200.50.181:8000
      - eureka.client.serviceUrl.defaultZone=http://infra-eureka-server:8761/eureka/
      - PROFILE=real
    restart: always
    networks:
      - mentoree-network

  reply-service:
    image: wer080/reply-service:1.0
    container_name: reply-service
    depends_on:
      - infra-config-server
      - infra-eureka-server
      - mentoree-redis
      - rabbitmq
    links:
      - infra-config-server
      - infra-eureka-server
      - mentoree-redis
      - rabbitmq
    environment:
      - spring.cloud.config.uri=http://infra-config-server:8888
      - spring.redis.host=http://mentoree-redis:6379
      - spring.rabbitmq.host=rabbitmq
      - Kafka.client.url=http://kafka:9092
      - Feign.url=http://43.200.50.181:8000
      - eureka.client.serviceUrl.defaultZone=http://infra-eureka-server:8761/eureka/
      - PROFILE=real
    restart: always
    networks:
      - mentoree-network

networks:
  mentoree-network:
    name: mentoree-network
    external: true